export { default as DashboardPage } from "./Dashboard.page";
export { default as LoginPage } from "./Auth/Login.page";
export { default as SprintPage } from "./Scrum/Sprint.page";
export { default as StoryPointsPage } from "./Scrum/StoryPoints.page";
export { default as StatisticsPage } from "./Accountabilities/Statistics.page";
export { default as TasksListPage } from "./Scrum/TasksList.page";
export { default as TestPage } from "./Test.page";
export { default as AppFlowPage } from "./AppFlow.page";
export { default as RequirementsDataPage } from "./Admin/RequirementsData.page";